name: test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install Dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build --no-restore
    - name: Run Test
      run: dotnet test --no-build --verbosity normal